### PR TITLE
Converted to VS2017

### PR DESCRIPTION
**Pull request by eswann**
I converted the project to VS 2017 and updated all references to most recent. 
Issue: I couldn't get the Environment variable MONGODB_HOST set up properly for VSTest in VS 2017.  I commented it out and just hard coded the Mongo connection string (for the moment). Maybe you have an idea on that.

### CODE REVIEW

**Comment by eswann** [comment]
In addition, I was unable to get the cake script working completely. The build was working, but tests were failing to run locally.

**Comment by ircnelson** [comment]
Hi @eswann I will don't integrate yet because I can't run on OSX. You did it?

**Comment by eswann** [comment]
Hi @ircnelson, I'll see if I can run manually on OSX and Linux.  The cake build is failing on OSX, but I think this is more about the build than the project.  I'm not well versed on Travis and Cake, but it's trying to install .Net 4.6.1 of Mono (doesn't exist) and it's failing for that reason.  Any ideas on that?  I'll try running the project manually on Linux and OSX and let you know what happens.

**Comment by eswann** [comment]
@ircnelson: All builds and tests now pass on Windows/Linux/OSX
OSX Travis CI takes a really long time and the mongo service doesn't work on OSX, so you have to install Mongo manually.

**Comment by ircnelson** [comment]
Thanks @eswann! :-)

**Comment by eswann** [comment]
@ircnelson One issue I still had outstanding...the logging of test output for OpenCover.  This no longer works with MSBuild: 
```
// ArgumentCustomization = args =>
//     args.Append("-xml").Append(testResultsDir.CombineWithFilePath(project.GetFilenameWithoutExtension()).FullPath + ".xml")
```
What I've seen says to switch to the following syntax, but I haven't been able to get that to work either:
ArgumentCustomization = args => args.Append("--logger:trx;LogFilePath=\"somepath.text.xml\"")

Do you have any ideas on that?  If not, I'm going to plug at it a little longer.

**Comment by ircnelson** [comment]
@eswann I don't have any idea... When I have more time I can try it.

**Pull request merged**
